### ISSUE TITLE
server.pl not found

### ISSUE THREAD

**Issue by tregobo** [freehackquest/perl-catalyst#1]
I am probably doing something wrong, but when I use the sample docker-compose file and do a build I get  the following error:

_PS C:\Users\tregobo\Documents\perl-catalyst> docker-compose up --build
[+] Running 2/2
 - Container perl-catalyst-perl_db-1               Running                                                                                                                                                                              0.0s
 - Container perl-catalyst-perl_catalyst_server-1  Recreated                                                                                                                                                                            0.1s
Attaching to perl-catalyst-perl_catalyst_server-1, perl-catalyst-perl_db-1
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "./server.pl": stat ./server.pl: no such file or directory: unknow_n
PS C:\Users\tregobo\Documents\perl-catalyst>

Thank you

**Comment by sea-kg** [comment]
All right. The current repository is just an example of building a system based on Perl + Catalyst Framework + PostgreSQL.
You must create the server.pl file yourself.

Maybe helpful:
https://metacpan.org/dist/Catalyst-Manual/view/lib/Catalyst/Manual/Tutorial/01_Intro.pod
